name: CI

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable corepack and pin pnpm
        run: |
          corepack enable
          # Pin pnpm to a specific version to avoid registry rate limits (429). Adjust version as needed.
          corepack prepare pnpm@10.15.0 --activate

      - name: Install & build server
        working-directory: server
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Install & build web
        working-directory: web
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
